sql_schema = """
CREATE TABLE top_5000 (
    id VARCHAR(255),
    symbol VARCHAR(255),
    name VARCHAR(255),
    image TEXT,
    current_price NUMERIC,
    market_cap NUMERIC,
    market_cap_rank NUMERIC,
    fully_diluted_valuation NUMERIC,
    total_volume NUMERIC,
    high_24h NUMERIC,
    low_24h NUMERIC,
    price_change_24h NUMERIC,
    price_change_percentage_24h NUMERIC,
    market_cap_change_24h NUMERIC,
    market_cap_change_percentage_24h NUMERIC,
    circulating_supply NUMERIC,
    total_supply NUMERIC,
    max_supply NUMERIC,
    ath NUMERIC,
    ath_change_percentage NUMERIC,
    ath_date TIMESTAMP,
    atl NUMERIC,
    atl_change_percentage NUMERIC,
    atl_date TIMESTAMP,
    roi TEXT,
    last_updated TIMESTAMP,
    price_change_percentage_1h_in_currency NUMERIC,
    price_change_percentage_24h_in_currency NUMERIC,
    price_change_percentage_7d_in_currency NUMERIC,
    fetched_timestamp TIMESTAMP,
    rank_change_1h FLOAT,
    rank_percent_change_1h FLOAT,
    rank_change_1d FLOAT,
    rank_percent_change_1d FLOAT,
    rank_change_7d FLOAT,
    rank_percent_change_7d FLOAT,
    rank_change_start FLOAT,
    rank_percent_change_start FLOAT
);
"""
